### ISSUE TITLE
Change with kicktipp? (Error: Not enough data, maybe there are no rates yet.)

### ISSUE THREAD

**Issue by qdlmcfresh** [schwalle/kicktipp-betbot#10]
For me parse_match_rows fails when creating a match.

```

match = Match(row[1].get_text(), row[2].get_text(), row[0].get_text(
            ), row[4].get_text().replace("/", ""), row[5].get_text().replace("/", ""), row[6].get_text())
```
Tried printing the rows to see where it fails and it seems like the rows list is of length 5 but should be at least 7
```
kicktippbb.py", line 117, in parse_match_rows
    row[5]: {row[5].get_text().replace('/', '')}\n
IndexError: list index out of range
```

**Comment by schwalle** [comment]
Yes there were chages on kicktipp.de page. I fixed it, so feel free to try the current master. if you dont reopen this issue i'll assume it is OK and create a new release.

**Comment by qdlmcfresh** [comment]
Working again, thanks :)
