### ISSUE TITLE
KeyError in get_predictors

### ISSUE THREAD

**Issue by tml89** [schwalle/kicktipp-betbot#3]
I got the follwoing Error if i try to run your bot: 

`Traceback (most recent call last):
  File "kicktippbb.py", line 256, in <module>
    main(arguments)
  File "kicktippbb.py", line 217, in main
    predictors = get_predictors()
  File "kicktippbb.py", line 210, in get_predictors
    return dict((name, obj) for name, obj in inspect.getmembers(sys.modules['prediction'], predicate=inspect.isclass) if 'predict' in [x for x, y in inspect.getmembers(obj, predicate=inspect.isfunction) if x == 'predict'])
KeyError: 'prediction'
`

**Comment by schwalle** [comment]
Thanks for the hint! 
I did some major restructuring of the code base, so feel free to try again.
